paths:
  /api/products:
    get:
      summary: 'Obtiene todos los productos'
      tags:
        - Products
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/products/search:
    get:
      summary: 'Busca productos por nombre'
      tags:
        - Products
      parameters:
        - name: productName
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string

  /api/products/category:
    get:
      summary: 'Obtiene productos por categoría'
      tags:
        - Products
      parameters:
        - name: categoryName
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string

  /api/product/{id}:
    get:
      summary: 'Obtiene un producto por ID'
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  product:
                    $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

    /api/product:
    post:
      summary: 'Añade un nuevo producto'
      tags:
        - Products
      requestBody:
        description: 'Datos obligatorios en el body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Product'
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: 'Parámetros insuficientes'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

    /api/product/{id}:
    put:
      summary: 'Actualiza un producto por ID'
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: 'Datos obligatorios en el body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateProduct'
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: 'Parámetros insuficientes'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/product/featured/{id}:
    put:
      summary: 'Activa o desactiva la característica destacada de un producto por ID'
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/product/offer/{id}:
    put:
      summary: 'Activa o desactiva la oferta de un producto por ID'
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

    /api/product/{id}:
    delete:
      summary: 'Elimina un producto por ID'
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "500":
          description: 'Error interno del servidor'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: 'Título del producto'
        description:
          type: string
          description: 'Descripción del producto'
        price:
          type: number
          description: 'Precio del producto'
        category:
          type: string
          description: 'ID de la categoría a la que pertenece el producto'
        images:
          type: array
          items:
            type: string
          description: 'Lista de URLs de imágenes del producto'
        code:
          type: string
          description: 'Código del producto'
        stock:
          type: number
          description: 'Cantidad en stock del producto'
      example:
        title: 'Nombre del producto'
        description: 'Descripción detallada del producto'
        price: 19.99
        category: '638b8c323f3a4b3be6dc397e'  # ID de la categoría
        images:
          - 'https://example.com/image1.jpg'
          - 'https://example.com/image2.jpg'
        code: 'ABC123'
        stock: 50

  requestBodies:
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: 'Título del producto'
        description:
          type: string
          description: 'Descripción del producto'
        price:
          type: number
          description: 'Precio del producto'
        category:
          type: string
          description: 'ID de la categoría a la que pertenece el producto'
        images:
          type: array
          items:
            type: string
          description: 'Lista de URLs de imágenes del producto'
        code:
          type: string
          description: 'Código del producto'
        stock:
          type: number
          description: 'Cantidad en stock del producto'
        isFeatured:
          type: boolean
          description: 'Indica si el producto es destacado'
        isOffer:
          type: boolean
          description: 'Indica si el producto está en oferta'
      example:
        title: 'Nuevo nombre del producto'
        description: 'Nueva descripción del producto'
        price: 24.99
        category: '738b8c323f3a4b3be6dc397f'  # Nuevo ID de categoría
        images:
          - 'https://example.com/new-image1.jpg'
          - 'https://example.com/new-image2.jpg'
        code: 'XYZ789'
        stock: 75
        isFeatured: true
        isOffer: false

    Product:
      type: object
      properties:
        title:
          type: string
          description: 'Título del producto'
        description:
          type: string
          description: 'Descripción del producto'
        price:
          type: number
          description: 'Precio del producto'
        category:
          type: string
          description: 'ID de la categoría a la que pertenece el producto'
        images:
          type: array
          items:
            type: string
          description: 'Lista de URLs de imágenes del producto'
        code:
          type: string
          description: 'Código del producto'
        stock:
          type: number
          description: 'Cantidad en stock del producto'
        isFeatured:
          type: boolean
          description: 'Indica si el producto es destacado'
        isOffer:
          type: boolean
          description: 'Indica si el producto está en oferta'
      example:
        title: 'Nombre del producto'
        description: 'Descripción detallada del producto'
        price: 19.99
        category: '638b8c323f3a4b3be6dc397e'  # ID de la categoría
        images:
          - 'https://example.com/image1.jpg'
          - 'https://example.com/image2.jpg'
        code: 'ABC123'
        stock: 50
        isFeatured: false
        isOffer: true
