openapi: 3.0.0
info:
  title: API de Tickets
  description: API para gestionar tickets de compra
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Desarrollo

paths:
  /api/tickets:
    get:
      summary: Obtiene todos los tickets
      tags:
        - Tickets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  tickets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ticket'
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/tickets/{id}:
    get:
      summary: Obtiene un ticket por ID
      tags:
        - Tickets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Ticket'
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

    delete:
      summary: Elimina un ticket por ID
      tags:
        - Tickets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

components:
  schemas:
    Ticket:
      type: object
      properties:
        amount:
          type: number
          description: Monto del ticket
        purchaser:
          type: string
          description: ID del comprador (Usuario)
      example:
        amount: 50.0
        purchaser: '638b8c323f3a4b3be6dc397e'  # ID del usuario
